# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_segundo_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veterinario',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='numero_contatcto',
            new_name='numero_contacto',
        ),
    ]
